### ISSUE TITLE
Compatibility with Laravel 6.x

### ISSUE THREAD

**Issue by cioraneanu** [eighty8-ventures/laravel-seeder#19]
When using with Laravel framework version 6.17.x, I get the following error because of the difference in method signture of `MigrationCreator::ensureMigrationDoesntAlreadyExist`

Error:
```
`Declaration of Eighty8\LaravelSeeder\Migration\SeederMigrationCreator::ensu  
  reMigrationDoesntAlreadyExist($name): void should be compatible with Illumi  
  nate\Database\Migrations\MigrationCreator::ensureMigrationDoesntAlreadyExis  
  t($name, $migrationPath = NULL)
```

**Comment by patsa** [comment]
Yes, also with Lumen 6.3.5.
Completely disables publishing because it throws a fatal error.

The change in Illuminate/Database is actually quite old:
https://github.com/illuminate/database/commit/a83af1a61aef241c9c253347b6e4d1c59887b703

**Comment by edmundluong88** [comment]
Hello @cioraneanu and @patsa,

Sorry for the inactivity lately, been fairly busy. I will have some capacity to look into resolving some of these compatibility issues for Laravel 6.x and 7.x soon, but feel free to make a PR otherwise.

Thanks!

**Comment by edmundluong88** [comment]
Hello @cioraneanu and @patsa ,

I have pushed a potential fix for 6.x streams. Please update this project to 6.1 and let me know if everything is resolved

**Comment by nerminba** [comment]
@edmundluong88 Hi, is this package still maintained activly?
