### ISSUE TITLE
Add support for multiple paths for seeders

### ISSUE THREAD

**Issue by renepardon** [eighty8-ventures/laravel-seeder#22]
Hello,

thanks so far for this great library!
I would like to be able to use it "easy way" in combination with nWidart modules. Every module inside the "Modules/" directory has it's own "database/" directory which contains corresponding migrations, seeds, factories. Would be nice if I can place the incremental seeders inside every module as instead of just the "database/seeders/" directory.

So within the configuration it should be possible to add multiple paths to seeders. Within the AbstractSeedMigrationCommand class there is a method called `resolveMigrationPaths`. It would be nice to have the array of paths merged by calling addMigrationPath for all of the configured paths (modules) as well.

**Comment by nerminba** [comment]
plus

**Comment by renepardon** [comment]
looks like this repository is dead. I took over and implemented this feature. I also changed code style to PSR-12 and increased the requirements to PHP 7.4 and laravel 7.

https://packagist.org/packages/renepardon/laravel-seeder

@nikocraft

**Comment by nerminba** [comment]
Good news, thanks for tagging me, I'll take a look at your fork! 👍
