### ISSUE TITLE
Seeders for several environments

### ISSUE THREAD

**Issue by stevevg** [eighty8-ventures/laravel-seeder#6]
I was wondering if it were possible to create a seeder for *all* environments of a project, instead of having to duplicate a seeder two or more times, thus avoiding code replication.

**Comment by edmundluong88** [comment]
Hi @stevevg ,

Thank you for raising this issue. This is something we currently do not have but I think it would make sense for there to be a directory where the seeders will be ran for "all" environments.

Currently, we have just been extending our production seeders and writing our environment-specific seeders in the child class (UserProdSeeder -> UserDevSeeder). This has been manageable for us for smaller projects with a small amount of seeded data, but for our medium/large size projects, we have run into a lot of code replication as you have mentioned.

What I would propose is creating an "all" environments directory in the seeders directory that will be ran EVERY time the seeders are ran, in addition to the environment specific seeders. This way, we can place all of the seeders that must be ran, regardless of environment, in a common directory, and then have the specific environment seeders run when appropriate.

Thoughts?

**Comment by stevevg** [comment]
I agree with you.
Moreover, talking about the order of execution of seeders, IMHO, these should run in an chronological order, despite directories/environments.
Let me explain more in detail: suppose we have a directory structure like this (in `database/seeders`):

- production
  - 2017_11_06_095000_bla1.php
- dev
  - 2017_11_10_095000_bla4.php
- all
  - 2016_01_27_112000_bla2.php
  - 2017_11_07_175000_bla3.php

When in `production`, seeders should run in the order bla2, bla1, bla3.
When in `dev`, seeders should run in the order bla2, bla3, bla4.

**Comment by edmundluong88** [comment]
That's a great idea! I am onboard with migrating the seeders based on chronological order.

I believe the seeder migrations are already ran in chronological order for a single environment since the seeder files are read in order. A simple solution would be to merge both the `all` environment directory with the target environment directory (`dev` for example), sort them and then migrate them.

I assume the batching/rollback behavior will remain the same? For example:

- production
  - 2017_11_06_095000_bla1.php
- dev
  - 2017_11_10_095000_bla4.php
- all
  - 2016_01_27_112000_bla2.php
  - 2017_11_07_175000_bla3.php

If we are currently using the `dev` environment and none of the migrations have been run, will both `all` seeders and the one `dev` seeder all be ran under `batch 1`? 

I currently do not have the capacity to implement this myself, but if you are interested and willing, I would be more than happy to accept a pull request!

Thanks!

**Comment by stevevg** [comment]
> If we are currently using the dev environment and none of the migrations have been run, will both all seeders and the one dev seeder all be ran under batch 1?

Yes, I would do that.

> I currently do not have the capacity to implement this myself, but if you are interested and willing, I would be more than happy to accept a pull request!

I don't either, but I may try, when I find some time (hopefully soon, since I need this feature :) ).

**Comment by edmundluong88** [comment]
Hi @stevevg

Happy New Year! I will be taking a look at this and will try and implement this in the next few days or so.

**Comment by stevevg** [comment]
Thanks Edmund, happy new year to you, too! This sounds great, I had no
spare time to code this feature, however I’ll follow your work.

**Comment by edmundluong88** [comment]
Hi @stevevg ,

I took a look at this today and it was surprisingly easy to implement the "all" environment feature by simply adding the "all" environment to the migrations path (see #7). It works as we described, where it looks in both the targeted environment and the "all" environment directories, sorts the seeders and runs them in batches. 

All the heavy lifting (sorting, combining of paths) is done by Laravel's Migrator class:

![migrator-getMigrationFiles](https://user-images.githubusercontent.com/29665373/34964297-e312aea8-fa1a-11e7-8fd8-e1de1abe75f8.png)

However, when the seeders are ran, we lose reference to the "all" env in the database, consider this scenario I have in my IDE:

![seeders](https://user-images.githubusercontent.com/29665373/34964359-320999d6-fa1b-11e7-9d26-a51542a6eee2.png)

As you can see, I have created four seeder classes in different environments:

- all
  - UserSeeder
  - UserSeederFour
- dev
  - UserSeederThree
- production
  - UserSeederTwo

and as expected, we have them running in the correct order. However, looking at the database, they are all ran under my current environment ("dev" in this case). 

In my usage, this wouldn't cause problems as it would be highly unlikely that I would mix/match environments without dumping the seeds anyways. I was wondering if you had any input on this before I merged it in? Do you think the "all" env should be preserved in the database?

Thanks!

**Comment by stevevg** [comment]
Good job!
I think the _all_ env may not be preserved in the DB, because, as you said, the environment is (usually) set according to the contents of the `.env` file; thus, it makes no sense IMHO changing environment without re-seeding the database.

**Comment by edmundluong88** [comment]
I agree! I will merge then. Thanks for the great feature suggestion.

**Comment by stevevg** [comment]
Ok, would you mind tagging a new release with this new feature?

**Comment by edmundluong88** [comment]
Done!

https://github.com/eighty8-ventures/laravel-seeder/releases/tag/5.5.1
