### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by ajzuse** [eighty8-ventures/laravel-seeder#8]
Are you planning to upgrade to laravel 5.6? 
currently the package does not allow the project to be upgraded to Laravel 5.6

Thank you for advance.

**Comment by edmundluong88** [comment]
Hi @ajzuse ,

We currently have no plans to upgrade to Laravel 5.6 at this time. However, if you wish to make a PR to help support Laravel 5.6, I would be more than happy to accept it!

Thanks!

**Comment by edmundluong88** [comment]
Hi @ajzuse ,

Thanks to @diegohq , Laravel 5.6 support has been added in #9 .

Thank you for your interest in the project!
